/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BotsRouteImport } from './routes/bots'
import { Route as BotsSlugRouteImport } from './routes/bots.$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSubmitRouteImport } from './routes/dashboard.submit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsRoute = BotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsSlugRoute = BotsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BotsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSubmitRoute = DashboardSubmitRouteImport.update({
  id: '/dashboard/submit',
  path: '/dashboard/submit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bots': typeof BotsRouteWithChildren
  '/bots/$slug': typeof BotsSlugRoute
  '/dashboard/submit': typeof DashboardSubmitRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bots': typeof BotsRouteWithChildren
  '/bots/$slug': typeof BotsSlugRoute
  '/dashboard/submit': typeof DashboardSubmitRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bots': typeof BotsRouteWithChildren
  '/bots/$slug': typeof BotsSlugRoute
  '/dashboard/submit': typeof DashboardSubmitRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bots'
    | '/bots/$slug'
    | '/dashboard/submit'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/auth' | '/bots' | '/bots/$slug' | '/dashboard/submit' | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bots'
    | '/bots/$slug'
    | '/dashboard/submit'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BotsRoute: typeof BotsRouteWithChildren
  DashboardSubmitRoute: typeof DashboardSubmitRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots': {
      id: '/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof BotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/$slug': {
      id: '/bots/$slug'
      path: '/$slug'
      fullPath: '/bots/$slug'
      preLoaderRoute: typeof BotsSlugRouteImport
      parentRoute: typeof BotsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/submit': {
      id: '/dashboard/submit'
      path: '/dashboard/submit'
      fullPath: '/dashboard/submit'
      preLoaderRoute: typeof DashboardSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BotsRouteChildren {
  BotsSlugRoute: typeof BotsSlugRoute
}

const BotsRouteChildren: BotsRouteChildren = {
  BotsSlugRoute: BotsSlugRoute,
}

const BotsRouteWithChildren = BotsRoute._addFileChildren(BotsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BotsRoute: BotsRouteWithChildren,
  DashboardSubmitRoute: DashboardSubmitRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
