/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BotsRouteImport } from './routes/bots'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BotsSlugRouteImport } from './routes/bots.$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSubmitRouteImport } from './routes/dashboard.submit'
import { Route as DashboardBotsIdEditRouteImport } from './routes/dashboard.bots.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsRoute = BotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsSlugRoute = BotsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BotsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSubmitRoute = DashboardSubmitRouteImport.update({
  id: '/dashboard/submit',
  path: '/dashboard/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBotsIdEditRoute = DashboardBotsIdEditRouteImport.update({
  id: '/dashboard/bots/$id/edit',
  path: '/dashboard/bots/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bots': typeof BotsRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/claim': typeof ClaimRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/bots/$slug': typeof BotsSlugRoute
  '/dashboard/submit': typeof DashboardSubmitRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/bots/$id/edit': typeof DashboardBotsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bots': typeof BotsRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/claim': typeof ClaimRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/bots/$slug': typeof BotsSlugRoute
  '/dashboard/submit': typeof DashboardSubmitRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/bots/$id/edit': typeof DashboardBotsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bots': typeof BotsRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/claim': typeof ClaimRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/bots/$slug': typeof BotsSlugRoute
  '/dashboard/submit': typeof DashboardSubmitRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/bots/$id/edit': typeof DashboardBotsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/bots'
    | '/categories'
    | '/claim'
    | '/contact'
    | '/privacy'
    | '/profile'
    | '/sitemap.xml'
    | '/terms'
    | '/bots/$slug'
    | '/dashboard/submit'
    | '/dashboard/'
    | '/dashboard/bots/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/bots'
    | '/categories'
    | '/claim'
    | '/contact'
    | '/privacy'
    | '/profile'
    | '/sitemap.xml'
    | '/terms'
    | '/bots/$slug'
    | '/dashboard/submit'
    | '/dashboard'
    | '/dashboard/bots/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/bots'
    | '/categories'
    | '/claim'
    | '/contact'
    | '/privacy'
    | '/profile'
    | '/sitemap.xml'
    | '/terms'
    | '/bots/$slug'
    | '/dashboard/submit'
    | '/dashboard/'
    | '/dashboard/bots/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BotsRoute: typeof BotsRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  ClaimRoute: typeof ClaimRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  DashboardSubmitRoute: typeof DashboardSubmitRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBotsIdEditRoute: typeof DashboardBotsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots': {
      id: '/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof BotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/$slug': {
      id: '/bots/$slug'
      path: '/$slug'
      fullPath: '/bots/$slug'
      preLoaderRoute: typeof BotsSlugRouteImport
      parentRoute: typeof BotsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/submit': {
      id: '/dashboard/submit'
      path: '/dashboard/submit'
      fullPath: '/dashboard/submit'
      preLoaderRoute: typeof DashboardSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/bots/$id/edit': {
      id: '/dashboard/bots/$id/edit'
      path: '/dashboard/bots/$id/edit'
      fullPath: '/dashboard/bots/$id/edit'
      preLoaderRoute: typeof DashboardBotsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BotsRouteChildren {
  BotsSlugRoute: typeof BotsSlugRoute
}

const BotsRouteChildren: BotsRouteChildren = {
  BotsSlugRoute: BotsSlugRoute,
}

const BotsRouteWithChildren = BotsRoute._addFileChildren(BotsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BotsRoute: BotsRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  ClaimRoute: ClaimRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  DashboardSubmitRoute: DashboardSubmitRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBotsIdEditRoute: DashboardBotsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
